<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MachineErpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $machines = [
            ['id' => 1, 'idMachine' => 'AA-00030', 'kode_room' => '*001612*', 'plant_name' => 'Plant E2', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Mixing', 'type_name' => 'Thermal Oil Heater', 'machine_type_id' => 7, 'brand_name' => 'ALPHA OMEGA', 'model_name' => 'S2.63.5', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 2, 'idMachine' => 'AA-00554', 'kode_room' => '*001615*', 'plant_name' => 'Plant E2', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Rubber', 'type_name' => 'Thermal Oil Heater', 'machine_type_id' => 7, 'brand_name' => 'SIN POONG', 'model_name' => 'SP-H50', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 3, 'idMachine' => 'AA-00507', 'kode_room' => '*001618*', 'plant_name' => 'Plant C', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Panel PJ112', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH2-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 4, 'idMachine' => 'AA-00508', 'kode_room' => '*001609*', 'plant_name' => 'Plant D', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PD', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 5, 'idMachine' => 'AA-00509', 'kode_room' => '*001609*', 'plant_name' => 'Plant D', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PD', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 6, 'idMachine' => 'AA-00544', 'kode_room' => '*001615*', 'plant_name' => 'Plant E2', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Rubber', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH2-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 7, 'idMachine' => 'AA-00570', 'kode_room' => '*001607*', 'plant_name' => 'Plant B', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PB', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 8, 'idMachine' => 'AA-00572', 'kode_room' => '*001606*', 'plant_name' => 'Plant A', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PA', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 9, 'idMachine' => 'ENG-00004', 'kode_room' => '*001606*', 'plant_name' => 'Plant A', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PA', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 10, 'idMachine' => 'AA-07251', 'kode_room' => '*001618*', 'plant_name' => 'Plant C', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Panel PJ112', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH2-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 11, 'idMachine' => 'AA-07268', 'kode_room' => '*001611*', 'plant_name' => 'Plant E1', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Grinding', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH3-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 12, 'idMachine' => 'AA-07269', 'kode_room' => '*001611*', 'plant_name' => 'Plant E1', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Grinding', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH2-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 13, 'idMachine' => 'AA-07270', 'kode_room' => '*001611*', 'plant_name' => 'Plant E1', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Grinding', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH2-100A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 14, 'idMachine' => 'AA-00575', 'kode_room' => '*001614*', 'plant_name' => 'Plant F', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility 2nd Process', 'type_name' => 'ECO AIR COMPRESSOR', 'machine_type_id' => 6, 'brand_name' => 'HANSHIN', 'model_name' => 'D-100', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 15, 'idMachine' => 'AA-07307', 'kode_room' => '*001609*', 'plant_name' => 'Plant D', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility PD', 'type_name' => 'ECO AIR COMPRESSOR', 'machine_type_id' => 6, 'brand_name' => 'HANSHIN', 'model_name' => 'D-100', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 16, 'idMachine' => 'AA-07475', 'kode_room' => '*001611*', 'plant_name' => 'Plant E1', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Grinding', 'type_name' => 'Compressor', 'machine_type_id' => 8, 'brand_name' => 'HANSHIN', 'model_name' => 'GRH-3 30A', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 17, 'idMachine' => 'ENG-00005', 'kode_room' => '*001611*', 'plant_name' => 'Plant E1', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Utility Grinding', 'type_name' => 'Generator Set', 'machine_type_id' => 9, 'brand_name' => 'CUMMINS', 'model_name' => '200KV ABC C 200 "CUMMINS"', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 18, 'idMachine' => 'ENG-00001', 'kode_room' => '*001347*', 'plant_name' => 'Mess Korea', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Pompa Banjir', 'type_name' => 'Generator Set', 'machine_type_id' => 9, 'brand_name' => 'CUMMINS', 'model_name' => 'CUMMIN KTA 19G4 500KVA/400KW', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 19, 'idMachine' => 'ENG-00002A', 'kode_room' => '*000078*', 'plant_name' => 'Engineering', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Panel MDB', 'type_name' => 'Generator Set', 'machine_type_id' => 9, 'brand_name' => 'CATERPILLAR', 'model_name' => 'CAT  3516 ,1.825 KVA', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
            ['id' => 20, 'idMachine' => 'ENG-00002B', 'kode_room' => '*000078*', 'plant_name' => 'Engineering', 'process_name' => 'Supporting', 'line_name' => 'Utility', 'room_name' => 'Panel MDB', 'type_name' => 'Generator Set', 'machine_type_id' => 9, 'brand_name' => 'CATERPILLAR', 'model_name' => 'CAT  3516 ,1.825 KVA', 'serial_number' => null, 'tahun_production' => null, 'no_document' => null, 'photo' => null, 'created_at' => '2025-11-26 20:50:22', 'updated_at' => '2025-11-28 19:34:33'],
        ];
        DB::table('machine_erp')->insert($machines);
    }
}

