<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredictiveMaintenanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Predictive Maintenance Schedules
        $schedules = [
            ['id' => 1, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-01-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 2, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-02-23', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 3, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-03-16', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 4, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-04-20', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 5, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-05-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 6, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-06-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 7, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-07-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 8, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-08-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 9, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-09-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 10, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-10-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 11, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-11-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 12, 'machine_erp_id' => 5, 'maintenance_point_id' => 1, 'standard_id' => 2, 'title' => 'Temperatur Motor Penggerak', 'description' => 'Cek Suhu Motor, agar motor selalu bekerja sesuai spek Motor', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-12-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 13, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-01-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 14, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-02-23', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 15, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-03-16', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 16, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-04-20', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 17, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-05-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 18, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-06-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 19, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-07-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 20, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-08-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 21, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-09-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 22, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-10-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 23, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-11-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 24, 'machine_erp_id' => 5, 'maintenance_point_id' => 2, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian belakang / NDE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-12-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 25, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-01-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 26, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-02-23', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 27, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-03-16', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 28, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-04-20', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 29, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-05-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 30, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-06-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 31, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-07-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 32, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-08-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 33, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-09-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 34, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-10-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 35, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-11-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 36, 'machine_erp_id' => 5, 'maintenance_point_id' => 3, 'standard_id' => 9, 'title' => 'Getaran Bearing Motor Penggerak (bagian depan / DE)', 'description' => 'Cek Getaran Motor, agar motor bekerja sesuai standard', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-12-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:21:00'],
            ['id' => 37, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-01-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 38, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-02-23', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 39, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-03-16', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 40, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-04-20', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 41, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-05-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 42, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-06-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 43, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-07-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 44, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-08-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 45, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-09-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 46, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-10-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 4, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 47, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-11-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 8, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
            ['id' => 48, 'machine_erp_id' => 5, 'maintenance_point_id' => 4, 'standard_id' => 13, 'title' => 'Penyebaran Suhu Motor', 'description' => 'Cek selisih suhu tertinggi dan terendah', 'frequency_type' => 'monthly', 'frequency_value' => 1, 'start_date' => '2024-12-19', 'end_date' => '2024-12-31', 'preferred_time' => null, 'estimated_duration' => null, 'status' => 'active', 'assigned_to' => 12, 'notes' => null, 'created_at' => '2025-11-30 17:50:32', 'updated_at' => '2025-11-30 19:33:08'],
        ];
        DB::table('predictive_maintenance_schedules')->insert($schedules);

        // Predictive Maintenance Executions
        $executions = [
            ['id' => 1, 'schedule_id' => 1, 'scheduled_date' => '2024-01-19', 'actual_start_time' => '2024-01-19 08:00:00', 'actual_end_time' => '2024-01-19 08:15:00', 'status' => 'completed', 'performed_by' => 4, 'measured_value' => 61.0000, 'measurement_status' => 'normal', 'findings' => null, 'actions_taken' => null, 'notes' => null, 'checklist' => null, 'cost' => null, 'photo_before' => null, 'photo_after' => null, 'created_at' => '2025-11-30 19:42:40', 'updated_at' => '2025-11-30 20:05:33'],
            ['id' => 2, 'schedule_id' => 13, 'scheduled_date' => '2024-01-19', 'actual_start_time' => null, 'actual_end_time' => null, 'status' => 'completed', 'performed_by' => 4, 'measured_value' => 1.4200, 'measurement_status' => 'normal', 'findings' => null, 'actions_taken' => null, 'notes' => null, 'checklist' => null, 'cost' => null, 'photo_before' => null, 'photo_after' => null, 'created_at' => '2025-11-30 19:42:40', 'updated_at' => '2025-11-30 19:42:40'],
            ['id' => 3, 'schedule_id' => 25, 'scheduled_date' => '2024-01-19', 'actual_start_time' => null, 'actual_end_time' => null, 'status' => 'completed', 'performed_by' => 4, 'measured_value' => 1.2000, 'measurement_status' => 'normal', 'findings' => null, 'actions_taken' => null, 'notes' => null, 'checklist' => null, 'cost' => null, 'photo_before' => null, 'photo_after' => null, 'created_at' => '2025-11-30 19:42:40', 'updated_at' => '2025-11-30 19:42:40'],
            ['id' => 4, 'schedule_id' => 37, 'scheduled_date' => '2024-01-19', 'actual_start_time' => null, 'actual_end_time' => null, 'status' => 'completed', 'performed_by' => 4, 'measured_value' => 2.0000, 'measurement_status' => 'normal', 'findings' => null, 'actions_taken' => null, 'notes' => null, 'checklist' => null, 'cost' => null, 'photo_before' => null, 'photo_after' => null, 'created_at' => '2025-11-30 19:42:40', 'updated_at' => '2025-11-30 20:04:35'],
        ];
        DB::table('predictive_maintenance_executions')->insert($executions);
    }
}
